rm(list = ls())

working_directory = "/Users/oscar/Documents/GitHub/NWBS"
setwd(working_directory)
#setwd(paste(working_directory,"/Code_J",sep=""))
source("utils_functions.R")
source('utils.R')

library(cumSeg)
library(strucchange)
library(Segmentor3IsBack)
library(changepoint)
library(stepR)
library(wbs)
library(changepoint.np)
M =  120
NMC = 20



#number of samples
T =  1000
K = 5

##############
##  Generate data   
theta =  rep(.2,K+1);
theta[2*(1:floor((K+1)/2))] =  1

v =  rep(0,K)##  set of change true change points
for(i in 1:K)
{
  v[i] = i*floor(T/(K+1))
} 


set.seed(2000)
y =  matrix(NA, T,1)###  samples
N = rep(1,T)    
for(t in 1:T)
{
  if( t<= v[1])
  {
    y[t,1:N[t]]  =  theta[1]*rnorm(1)  
  }
  if(K >1)
  {
    for(j in 1:(K-1))
    {
      if(  t >  v[j]   &&  t <=  v[j+1])
      {
        y[t,1:N[t]]  =   theta[j+1]*rnorm(1)
      }
    }
  }
  if(t > v[K])
  {
    y[t,1:N[t]]  = theta[K+1]*rnorm(1)
  }
}    

######################################
### WNBS

M =   120
alpha =  sample.int(size =M  , n = T,replace = TRUE)
beta =   sample.int(size =M  , n = T,replace = TRUE)#alpha + floor((T- alpha)*runif(M))
#
for(j in 1:M)
{
  aux =  alpha[j]
  aux2 =  beta[j]
  #
  alpha[j] = min(aux,aux2)
  beta[j] = max(aux,aux2)
}


temp_wbs = new_WBS(y, s=1,e=T,alpha=alpha,beta=beta,N=N) ## structure used to find potential change points
Dval = temp_wbs$Dval ##  values  of statistic at potential change points
p =  parent(temp_wbs)###  tree structure generated by WBS
values = sort(Dval,decreasing = TRUE)
tau_grid = rev(values[1:min(20,length(Dval))]-10^{-5})
tau_grid = c(tau_grid,10)

##  An example
tau =  tau_grid[16]
S = sort(new_BS_threshold(temp_wbs,tau,p))
S  #estimated change points
v  # true change points
